version: '3.8'
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data:cached
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  postgres:
